import type { Metadata } from "next";
import Link from "next/link";
import { pretendard } from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: "/images/favicon.ico" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <div className="flex h-full flex-col">
          <nav className="flex h-12 items-center border-b  bg-white px-5 text-black">
            <ul className="flex space-x-3">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/test">Test</Link>
              </li>
            </ul>
          </nav>
          <div className="flex grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
