import type { Metadata } from "next";
import { pretendard } from "@/fonts";
import "./globals.css";

import MainHeader from "@/components/organisms/MainHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: "/images/favicon.ico" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <div className="flex h-full flex-col">
          <MainHeader />
          <div className="flex grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
