#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\nPre-push Hook..."

# knip(사용하지 않은 파일 체크) 실행
echo "\n>> 사용하지 않는 파일이 있는지 체크"

npm run knip

echo "\n>> 파일 체크 끝 -> 목록이 있다면 확인해주세요!\n"

# 보호 브랜치에 푸시하고 있는지 여부 체크
# echo "\n>> Checking branch name\n"
echo "\n>> 보호 브랜치에 push중인지 확인\n"

# 현재 체크아웃된 브랜치
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
# 직접 push하면 안되는 보호 브랜치
PROTECTED_BRANCHES="main dev"

echo "보호 브랜치(들): $PROTECTED_BRANCHES"
echo "현재 브랜치: $CURRENT_BRANCH\n"

for BRANCH in $PROTECTED_BRANCHES
do
  # 현재 브랜치가 보호 브랜치면 push 취소 처리
  if [ "$BRANCH" = "$CURRENT_BRANCH" ]
  then
    echo "🚫 보호 브랜치에 직접 push할 수 없습니다."
    echo "🚫 신규 브랜치로부터 push한 후 PR해주세요!\n"
    exit 1
    break
  fi
done

# echo ">> Finish checking branch name.\n"
echo ">> 안전하게 push중! ^.^/\n"

exit 0
